### PR TITLE
Patch to work for Arch Linux

### PR DESCRIPTION
**Pull request by madsciencecoder**
Hello, I was having trouble getting this to work in Arch Linux because the functions tostring() and fromstring() were removed and seem to work if you replace them with tobytes() and frombytes().

### CODE REVIEW

**Comment by tibor95** [comment]
Hi, I am using Arch Linux as well, and it works here. Can you describe more in detail what type of problems and since when you have?

**Comment by madsciencecoder** [comment]
I first tried installing it from the AUR at https://aur.archlinux.org/packages/phatch/ and when trying to run it the program wouldn't start so trying it from the terminal to get some output gave me: 

> [$USER@sherlock phatch-python2.7]$ ./run.sh
> 01:07:43 AM: Warning: Mismatch between the program and library build versions detected.
> The library used 3.0 (wchar_t,compiler with C++ ABI 1008,wx containers,compatible with 2.8),
> and wxPython used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8).
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 16762, in <lambda>
>     lambda event: event.callable(_event.args, *_event.kw) )
>   File "/home/$USER/phatch-python2.7/phatch/pyWx/gui.py", line 1222, in show_frame
>     frame = Frame(self.filename, None, -1, ct.TITLE)
>   File "/home/$USER/phatch-python2.7/phatch/pyWx/gui.py", line 327, in __init__
>     frame.Frame.**init**(self, _args, *_keyw)
>   File "/home/$USER/phatch-python2.7/phatch/pyWx/wxGlade/frame.py", line 141, in **init**
>     self.tree = Tree(self, -1, style=wx.TR_HAS_BUTTONS|wx.TR_NO_LINES|wx.TR_FULL_ROW_HIGHLIGHT|wx.TR_HIDE_ROOT|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
>   File "/home/$USER/phatch-python2.7/phatch/pyWx/wxGlade/frame.py", line 26, in **init**
>     set_dirty   = parent.set_dirty,
>   File "/home/$USER/phatch-python2.7/phatch/lib/pyWx/treeEdit.py", line 96, in **init**
>     self.CreateImageList(icon_size)
>   File "/home/$USER/phatch-python2.7/phatch/lib/pyWx/treeEdit.py", line 111, in CreateImageList
>     self._AddFormToImageList(form, icon_size, icon_disabled)
>   File "/home/$USER/phatch-python2.7/phatch/lib/pyWx/treeEdit.py", line 121, in _AddFormToImageList
>     Image.ANTIALIAS))
>   File "/home/$USER/phatch-python2.7/phatch/lib/pyWx/wxPil.py", line 34, in pil_wxImage
>     data = new_image.tostring()
>   File "/usr/lib/python2.7/site-packages/PIL/Image.py", line 686, in tostring
>     "Please call tobytes() instead.")
> Exception: tostring() has been removed. Please call tobytes() instead.

It did this for each instance of where tostring() or fromstring() existed which only happened to be in the 5 places.  This error happened on both my machine and my friend's so I decided to modify the functions as it suggested which fixed the problem and thought I would share it.

I encountered the error last night when I tried to install the program to help my friend get it to work.

**Comment by tibor95** [comment]
Oh, I understand.

In fact this is not the source for AUR. The project itself is dead and there are multiple mirrors/forks of this on network. This one has been patched a bit and should be working on archlinux and debian.

If you want, download it and test it. I put there run.sh script, so just double click should run the program.

If you still have problem, let me know.....

**Comment by madsciencecoder** [comment]
Sorry for not clarifying.  I had the same problem with both the AUR version and yours.  I found your repository linked in the comments and tried this one after the AUR one didn't work.

I did a little research about it and seems to be a problem with python-pillow deprecating the tostring() and fromstring() functions.  I found a discussion about it at https://github.com/python-pillow/Pillow/issues/63 which seems to indicate they are aliased to tobytes() and frombytes().  I could very well be using a different version of python-pillow which might explain why I have the issue and you don't.  I have version 3.0.0-1 for both python2-pillow and python3-pillow.

**Comment by tibor95** [comment]
I cannot look at my archlinux now, but on debian I have v 2.6.1-1+b1. I will test your version on both my boxes and if it will work on both of them I will merge this. If not - I will see

**Comment by tibor95** [comment]
Merged. Thanks for input!

**Pull request merged**
